// Fuente única de verdad de TODOS los códigos de error del dominio cron.
export const CRON_ERROR_CODES = {
  INVALID_CRON_EXPRESSION: "INVALID_CRON_EXPRESSION",
  JOB_NOT_FOUND: "JOB_NOT_FOUND",

  SCHEDULER_START_FAILED: "SCHEDULER_START_FAILED",
  SCHEDULER_STOP_FAILED: "SCHEDULER_STOP_FAILED",
  SCHEDULER_ALREADY_RUNNING: "SCHEDULER_ALREADY_RUNNING",
  SCHEDULER_NOT_RUNNING: "SCHEDULER_NOT_RUNNING",

  INFRASTRUCTURE_ERROR: "INFRASTRUCTURE_ERROR",
} as const;

export type CronErrorCode =
  (typeof CRON_ERROR_CODES)[keyof typeof CRON_ERROR_CODES];

export type SchedulerErrorCode =
  | typeof CRON_ERROR_CODES.SCHEDULER_START_FAILED
  | typeof CRON_ERROR_CODES.SCHEDULER_STOP_FAILED
  | typeof CRON_ERROR_CODES.SCHEDULER_ALREADY_RUNNING
  | typeof CRON_ERROR_CODES.SCHEDULER_NOT_RUNNING
  | typeof CRON_ERROR_CODES.INFRASTRUCTURE_ERROR;
